### ISSUE TITLE
ValueError: You can't pass load_in_4bit or load_in_8bit as a kwarg when passing quantization_config argument at the same time.

### ISSUE THREAD

**Issue by u6vup** [ambroser53/LLaMA-Day-Care#3]
First of all, thank you for sharing your amazing project!
I encountered an issue when trying to run the code. I am using  Python 3.12.5 on Windows, with Transformers version 4.44.2. While running the code, I experienced the following error:
**ValueError: You can't pass load_in_4bitor load_in_8bit as a kwarg when passing quantization_config argument at the same time.**
Could you please clarify how I should adjust the code to resolve this issue?
Thank you so much for your time and help!

**Comment by snackycracky** [comment]
dup https://github.com/ambroser53/Prompt-Day-Care/issues/4 
why did you close this? Did did get it to work ?
